
x-shared-env: &shared-env
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: dev-password
  POSTGRES_DB: me

services:
    web-app:
        environment:
            <<: *shared-env
            FLASK_ENV: development
            DB_HOST: postgres
            DB_PORT: 5432
    caddy:
        volumes:
            - ${PWD}/conf/dev:/etc/caddy:ro
            # Allow CA root cert install (development only)
            - type: tmpfs
              target: /usr/local/share/ca-certificates
            - type: tmpfs
              target: /etc/ssl/certs
        ports:
            - "8081:8081"
    postgres:
      environment:
        <<: *shared-env
