
services:
  web-app:
    environment:
      FLASK_ENV: production
      DATABASE_URL: postgresql://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:5432/${DB_NAME}
  caddy:
    volumes:
      - ./conf/prod:/etc/caddy:ro
      # for goaccess dashboard -> expose html and logs
      - caddy_log:/logs
      - goaccess_html:/usr/share/caddy/html:ro
    environment:
      HOST_DOMAIN: ${HOST_DOMAIN}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"

  goaccess:
    image: allinurl/goaccess:latest
    volumes:
      - ./goaccess/goaccess.conf:/srv/config/goaccess.conf:ro
      - caddy_log:/srv/logs:ro  # read the combined log from Caddy
      - ./goaccess/geo:/geo:ro  # GeoIP DB
      - goaccess_html:/usr/share/caddy/html:rw  # where the HTML lives
    depends_on:
      - caddy
    command: ["--no-global-config", 
              "--config-file=/srv/config/goaccess.conf", 
    "--ws-url=wss://${HOST_DOMAIN}:443/stats/socket"
             ]
    restart: unless-stopped  
    networks:
      - backend
  postgres:
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}

volumes:
  certs: {}
  vhost: {}
  html: {}
  acme: {}
  caddy_log: {}
