
services:
  web-app:
    build: .
    container_name: web_app_jan
    restart: unless-stopped
    depends_on:
      - postgres
    links:
      - postgres
    networks:
      - backend
    volumes:
      - ./src:/home/app/src
  caddy:
    image: caddy:2.10
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    volumes:
      - caddy_data:/data
      - caddy_config:/config
    tmpfs:
      - /tmp
    links:
      - web-app
    depends_on:
      - web-app
    networks:
      - backend
    read_only: true
  postgres:
    image: postgres:17.4
    container_name: postgres_jan
    restart: unless-stopped
    tmpfs:
      - /run
      - /tmp
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend
    read_only: true

volumes:
  caddy_data: {}
  caddy_config: {}
  pgdata: {}
  goaccess_html: {}

networks:
  backend: {}
