
services:
  web-app:
    build: .
    container_name: web_app_jan
    restart: unless-stopped
    depends_on:
      - postgres
    links:
      - postgres
    networks:
      - backend
    volumes:
      - ./src:/home/app/src
  caddy:
    image: caddy:2.10
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    volumes:
      - caddy_data:/data
      - caddy_config:/config
      # for goaccess dashboard -> expose html and logs
      - ./logs:/logs
      - goaccess_html:/usr/share/caddy/html:ro
     # - access_logs:/var/log/access.log
    tmpfs:
      - /tmp
    links:
      - web-app
    depends_on:
      - web-app
    networks:
      - backend
    read_only: true
    #command: ["sh", "-c", "touch /var/log/access.log && caddy run"]
  goaccess:
    image: allinurl/goaccess:latest
    command: >
      sh -c "goaccess /logs/access.log
             --log-format=CADDY
             --date-format=%s \
             --time-format=%s \
             --real-time-html
             --geoip-database=/geo/GeoLite2-Country.mmdb
             -o /usr/share/caddy/html/index.html
             --daemonize"
    volumes:
      - ./logs:/logs:ro  # read the combined log from Caddy
      - ./geo:/geo:ro  # GeoIP DB
      - goaccess_html:/usr/share/caddy/html  # where the HTML lives
    depends_on:
      - caddy
  postgres:
    image: postgres:17.4
    container_name: postgres_jan
    restart: unless-stopped
    tmpfs:
      - /run
      - /tmp
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend
    read_only: true

volumes:
  caddy_data: {}
  caddy_config: {}
  pgdata: {}
  goaccess_html: {}
  access_logs: {}

networks:
  backend: {}
